# Generated by Django 5.2.14 on 2026-05-24 01:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=20, verbose_name='Numero de parcelle')),
                ('superficie', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Superficie (m2)')),
                ('longueur', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('largeur', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('prix', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Prix (FCFA)')),
                ('prix_negocie', models.BooleanField(default=False, verbose_name='Prix negotiable')),
                ('en_promotion', models.BooleanField(default=False, verbose_name='En promotion')),
                ('prix_promo', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True)),
                ('promo_fin', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('reservee', 'Reservee'), ('vendue', 'Vendue'), ('indisponible', 'Indisponible')], default='disponible', max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('geojson', models.JSONField(blank=True, null=True, verbose_name='GeoJSON polygone')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('caracteristiques', models.JSONField(blank=True, default=dict)),
                ('featured', models.BooleanField(default=False)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Parcelle',
                'verbose_name_plural': 'Parcelles',
                'ordering': ['site', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='SiteFoncier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du site')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(verbose_name='Description complete')),
                ('description_courte', models.CharField(max_length=300, verbose_name='Description courte')),
                ('localisation', models.CharField(max_length=200, verbose_name='Localisation')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('quartier', models.CharField(blank=True, max_length=100, verbose_name='Quartier')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('zoom_carte', models.PositiveSmallIntegerField(default=16)),
                ('image_principale', models.ImageField(blank=True, null=True, upload_to='sites/images/', verbose_name='Image principale')),
                ('video_drone', models.URLField(blank=True, verbose_name='Video drone (URL)')),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('en_cours', 'En cours de vente'), ('complet', 'Complet'), ('prochainement', 'Prochainement')], default='disponible', max_length=20)),
                ('prix_min', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='Prix minimum (FCFA)')),
                ('prix_max', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='Prix maximum (FCFA)')),
                ('superficie_totale', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('featured', models.BooleanField(default=False, verbose_name='Mis en avant')),
                ('en_promotion', models.BooleanField(default=False, verbose_name='En promotion')),
                ('promotion_description', models.CharField(blank=True, max_length=200)),
                ('promotion_fin', models.DateTimeField(blank=True, null=True)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site foncier',
                'verbose_name_plural': 'Sites fonciers',
                'ordering': ['ordre', '-featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImageParcelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='parcelles/images/')),
                ('legende', models.CharField(blank=True, max_length=200)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='eden.parcelle')),
            ],
            options={
                'verbose_name': 'Image parcelle',
                'verbose_name_plural': 'Images parcelle',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(blank=True, max_length=20, unique=True)),
                ('nom_client', models.CharField(max_length=150, verbose_name='Nom client')),
                ('email_client', models.EmailField(max_length=254, verbose_name='Email client')),
                ('telephone_client', models.CharField(max_length=20, verbose_name='Telephone')),
                ('montant_total', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Montant total (FCFA)')),
                ('montant_acompte', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmee'), ('acompte_verse', 'Acompte verse'), ('payee', 'Entierement payee'), ('annulee', 'Annulee')], default='en_attente', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='eden.parcelle')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='parcelle',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelles', to='eden.sitefoncier', verbose_name='Site'),
        ),
        migrations.CreateModel(
            name='ImageSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sites/gallery/')),
                ('legende', models.CharField(blank=True, max_length=200)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='eden.sitefoncier')),
            ],
            options={
                'verbose_name': 'Image du site',
                'verbose_name_plural': 'Images du site',
                'ordering': ['ordre', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='DemandeContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(max_length=20, verbose_name='Telephone')),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('type_demande', models.CharField(choices=[('achat', "Demande d'achat"), ('visite', 'Demande de visite'), ('information', "Demande d'information"), ('reservation', 'Reservation'), ('autre', 'Autre')], default='information', max_length=20)),
                ('message', models.TextField(verbose_name='Message')),
                ('budget', models.CharField(blank=True, max_length=50)),
                ('statut', models.CharField(choices=[('nouveau', 'Nouveau'), ('en_cours', 'En cours'), ('traite', 'Traite'), ('ferme', 'Ferme')], default='nouveau', max_length=20)),
                ('notes_internes', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parcelle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes', to='eden.parcelle')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes', to='eden.sitefoncier')),
            ],
            options={
                'verbose_name': 'Demande de contact',
                'verbose_name_plural': 'Demandes de contact',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Temoignage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du client')),
                ('role', models.CharField(blank=True, max_length=100, verbose_name='Profession / Ville')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='temoignages/')),
                ('texte', models.TextField(verbose_name='Temoignage')),
                ('note', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('is_active', models.BooleanField(default=True, verbose_name='Visible')),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temoignages', to='eden.sitefoncier')),
            ],
            options={
                'verbose_name': 'Temoignage',
                'verbose_name_plural': 'Temoignages',
                'ordering': ['ordre', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisiteProgrammee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom_client', models.CharField(max_length=150)),
                ('telephone_client', models.CharField(max_length=20)),
                ('email_client', models.EmailField(max_length=254)),
                ('date_visite', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('demandee', 'Demandee'), ('confirmee', 'Confirmee'), ('effectuee', 'Effectuee'), ('annulee', 'Annulee')], default='demandee', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visites', to='eden.sitefoncier')),
            ],
            options={
                'verbose_name': 'Visite programmee',
                'verbose_name_plural': 'Visites programmees',
                'ordering': ['-date_visite'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='parcelle',
            unique_together={('site', 'numero')},
        ),
    ]
