# Generated by Django 5.2.14 on 2026-06-03 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eden', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupyCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Catégorie')),
                ('emoji', models.CharField(default='💬', max_length=10)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Catégorie GROUPY',
                'verbose_name_plural': 'Catégories GROUPY',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='GroupyQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Question (ou variantes séparées par |)')),
                ('reponse', models.TextField(verbose_name='Réponse')),
                ('mots_cles', models.TextField(blank=True, help_text='Ex: prix, tarif, coût, combien', verbose_name='Mots-clés déclencheurs (séparés par virgule)')),
                ('priorite', models.PositiveSmallIntegerField(default=0, verbose_name='Priorité (plus haut = vérifié en premier)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('nb_utilisations', models.PositiveIntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='eden.groupycategorie')),
            ],
            options={
                'verbose_name': 'Q&R GROUPY',
                'verbose_name_plural': 'Base de connaissances GROUPY',
                'ordering': ['-priorite', '-nb_utilisations'],
            },
        ),
    ]
