# Generated by Django 5.2.15 on 2026-06-30 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eden', '0002_groupycategorie_groupyqr'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name="Titre de l'édition")),
                ('numero', models.PositiveIntegerField(unique=True, verbose_name='Numéro')),
                ('sous_titre', models.CharField(blank=True, max_length=300)),
                ('image_une', models.ImageField(blank=True, null=True, upload_to='journal/unes/', verbose_name='Image à la Une')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publié'), ('archive', 'Archivé')], default='brouillon', max_length=20)),
                ('date_parution', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Édition du journal',
                'verbose_name_plural': 'Éditions du journal',
                'ordering': ['-numero'],
            },
        ),
        migrations.CreateModel(
            name='JournalMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('image', 'Image'), ('video', 'Vidéo')], max_length=10)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='journal/medias/')),
                ('url_externe', models.URLField(blank=True, help_text='URL YouTube/Vimeo')),
                ('legende', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='eden.journaledition')),
            ],
            options={
                'verbose_name': 'Média journal',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(verbose_name='Numéro de page')),
                ('contenu', models.JSONField(blank=True, default=list, verbose_name='Contenu (blocs)')),
                ('layout', models.CharField(choices=[('une', 'Une (pleine page)'), ('col1', '1 colonne'), ('col2', '2 colonnes'), ('col3', '3 colonnes')], default='col2', max_length=20)),
                ('couleur_fond', models.CharField(default='#FFFEF7', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='eden.journaledition')),
            ],
            options={
                'verbose_name': 'Page du journal',
                'ordering': ['numero'],
                'unique_together': {('edition', 'numero')},
            },
        ),
    ]
