# Generated by Django 5.2.15 on 2026-07-08 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eden', '0003_journaledition_journalmedia_journalpage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteStatistiquesManuelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_parcelles_manuel', models.PositiveIntegerField(default=0, verbose_name='Total parcelles (saisi manuellement)')),
                ('vendues_manuel', models.PositiveIntegerField(default=0, verbose_name='Parcelles vendues')),
                ('disponibles_manuel', models.PositiveIntegerField(default=0, verbose_name='Parcelles disponibles')),
                ('reservees_manuel', models.PositiveIntegerField(default=0, verbose_name='Parcelles réservées')),
                ('indisponibles_manuel', models.PositiveIntegerField(default=0, verbose_name='Parcelles indisponibles')),
                ('prix_min_manuel', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='Prix minimum (FCFA)')),
                ('prix_max_manuel', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='Prix maximum (FCFA)')),
                ('prix_moyen_manuel', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='Prix moyen (FCFA)')),
                ('superficie_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Superficie min (m²)')),
                ('superficie_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Superficie max (m²)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('derniere_maj', models.DateTimeField(auto_now=True)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats_manuelles', to='eden.sitefoncier')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Statistiques manuelles site',
            },
        ),
    ]
