# Generated by Django 5.2.15 on 2026-07-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eden', '0004_sitestatistiquesmanuelle'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_fond', models.ImageField(blank=True, null=True, upload_to='hero/', verbose_name='Image de fond (hero)')),
                ('eyebrow', models.CharField(blank=True, default='Plateforme Foncière N°1 — Afrique Centrale', max_length=200, verbose_name='Texte au-dessus du titre')),
                ('titre_ligne1', models.CharField(blank=True, default='Votre terrain de rêve,', max_length=200, verbose_name='Titre ligne 1')),
                ('titre_ligne2', models.CharField(blank=True, default='trouvé en quelques clics.', max_length=200, verbose_name='Titre ligne 2 (accentuée)')),
                ('description', models.TextField(blank=True, default='Découvrez les meilleures parcelles foncières. Visualisez en satellite, explorez la carte et sécurisez votre investissement.', verbose_name='Description sous le titre')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration Hero (accueil)',
            },
        ),
    ]
