# Generated by Django 5.2.15 on 2026-07-10 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eden', '0005_heroconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualiteHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description courte')),
                ('image', models.ImageField(blank=True, null=True, upload_to='actualites/', verbose_name='Image')),
                ('date_evenement', models.DateField(blank=True, null=True, verbose_name="Date de l'événement")),
                ('lien', models.CharField(blank=True, default='#', max_length=200, verbose_name="Lien 'En savoir plus'")),
                ('is_active', models.BooleanField(default=True)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Actualité / Événement',
                'verbose_name_plural': 'Actualités & Événements',
                'ordering': ['-date_evenement', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='CommentaireHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du client')),
                ('role', models.CharField(blank=True, max_length=100, verbose_name='Rôle / Ville')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='commentaires/', verbose_name='Photo du client')),
                ('texte', models.TextField(verbose_name='Commentaire')),
                ('note', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5, verbose_name='Note (étoiles)')),
                ('is_active', models.BooleanField(default=True)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Commentaire client (home)',
                'verbose_name_plural': 'Commentaires clients (home)',
                'ordering': ['ordre', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EtapeAcquisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(verbose_name="Numéro d'étape")),
                ('titre', models.CharField(max_length=100, verbose_name="Titre de l'étape")),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Description courte')),
                ('couleur', models.CharField(choices=[('blue', 'Bleu'), ('red', 'Rouge')], default='blue', max_length=20, verbose_name='Couleur du cercle')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "Étape d'acquisition",
                'verbose_name_plural': "Étapes d'acquisition",
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='SectionLivret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_principal', models.CharField(default='Le Livret de Sécurité EDEN GROUP', max_length=200, verbose_name='Titre principal')),
                ('sous_titre', models.CharField(blank=True, default='Un système unique garantissant la sécurisation physique et numérique de tous vos documents fonciers.', max_length=300, verbose_name='Sous-titre')),
                ('image', models.ImageField(blank=True, null=True, upload_to='livret/', verbose_name='Image du livret')),
                ('badge_texte', models.CharField(blank=True, default='Notre engagement', max_length=100, verbose_name='Texte du badge')),
                ('btn_texte', models.CharField(blank=True, default='Découvrir le Livret', max_length=80, verbose_name='Texte du bouton')),
                ('btn_lien', models.CharField(blank=True, default='#', max_length=200, verbose_name='Lien du bouton')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Section Livret de Sécurité',
            },
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150, verbose_name='Titre du service')),
                ('description', models.TextField(verbose_name='Description')),
                ('icone', models.CharField(default='🏡', help_text='Ex: 🏡 🗺 🔒 ⚡ 📄', max_length=10, verbose_name='Icône emoji')),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='StatistiqueHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.CharField(help_text='Ex: 20+, 10 000+, 100%, 50+', max_length=20, verbose_name='Valeur affichée')),
                ('label', models.CharField(max_length=80, verbose_name='Label')),
                ('icone', models.CharField(blank=True, default='📊', max_length=10, verbose_name='Icône emoji')),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Statistique (bande chiffres)',
                'verbose_name_plural': 'Statistiques (bande chiffres)',
                'ordering': ['ordre'],
            },
        ),
        migrations.AlterModelOptions(
            name='heroconfig',
            options={'verbose_name': "Configuration Hero (page d'accueil)"},
        ),
        migrations.AddField(
            model_name='heroconfig',
            name='badge_site_lieu',
            field=models.CharField(blank=True, default='Yaoundé - voie de contournement', max_length=100, verbose_name='Lieu dans le badge hero'),
        ),
        migrations.AddField(
            model_name='heroconfig',
            name='badge_site_nom',
            field=models.CharField(blank=True, default='Site : MVÉ 1', max_length=100, verbose_name='Nom du site dans le badge hero'),
        ),
        migrations.AddField(
            model_name='heroconfig',
            name='btn1_texte',
            field=models.CharField(blank=True, default='Découvrir nos terrains', max_length=80),
        ),
        migrations.AddField(
            model_name='heroconfig',
            name='btn2_texte',
            field=models.CharField(blank=True, default='Visite des sites', max_length=80),
        ),
        migrations.AlterField(
            model_name='heroconfig',
            name='description',
            field=models.TextField(blank=True, default="EDEN GROUP vous accompagne dans l'acquisition, l'aménagement et la sécurisation de vos terrains avec professionnalisme et transparence.", verbose_name='Description sous le titre'),
        ),
        migrations.AlterField(
            model_name='heroconfig',
            name='image_fond',
            field=models.ImageField(blank=True, null=True, upload_to='hero/', verbose_name='Image de fond du hero'),
        ),
        migrations.AlterField(
            model_name='heroconfig',
            name='titre_ligne1',
            field=models.CharField(blank=True, default="Investissez aujourd'hui", max_length=200, verbose_name='Titre ligne 1'),
        ),
        migrations.AlterField(
            model_name='heroconfig',
            name='titre_ligne2',
            field=models.CharField(blank=True, default='dans un avenir sécurisé.', max_length=200, verbose_name='Titre ligne 2 (accentuée en rouge)'),
        ),
        migrations.CreateModel(
            name='AvantagesLivret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=200, verbose_name='Avantage')),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('livret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avantages', to='eden.sectionlivret')),
            ],
            options={
                'verbose_name': 'Avantage du livret',
                'verbose_name_plural': 'Avantages du livret',
                'ordering': ['ordre'],
            },
        ),
    ]
