# Generated by Django 5.2.15 on 2026-07-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eden', '0006_actualitehome_commentairehome_etapeacquisition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hero/slides/', verbose_name='Image de fond')),
                ('titre', models.CharField(blank=True, max_length=200, verbose_name='Titre (optionnel)')),
                ('sous_titre', models.CharField(blank=True, max_length=300, verbose_name='Sous-titre (optionnel)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Visible sur le site')),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Slide Hero',
                'verbose_name_plural': 'Slides Hero (carrousel)',
                'ordering': ['ordre', '-created_at'],
            },
        ),
    ]
