# Generated by Django 5.2.15 on 2026-07-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eden', '0007_heroslide'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroconfig',
            name='etapes_image',
            field=models.ImageField(blank=True, null=True, upload_to='etapes/', verbose_name="Image technicien (section étapes d'acquisition)"),
        ),
    ]
