# Generated by Django 5.2.15 on 2026-07-17 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eden', '0008_heroconfig_etapes_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UneEvenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('une', 'À la Une'), ('evenement_avenir', 'Événement à venir'), ('evenement_passe', 'Événement passé'), ('actualite', 'Actualité')], default='actualite', max_length=30, verbose_name='Catégorie')),
                ('titre', models.CharField(max_length=300, verbose_name='Titre')),
                ('sous_titre', models.CharField(blank=True, max_length=400, verbose_name='Sous-titre / Accroche')),
                ('image_couverture', models.ImageField(blank=True, null=True, upload_to='une_evenements/couvertures/', verbose_name='Image de couverture')),
                ('date_evenement', models.DateField(blank=True, null=True, verbose_name="Date de l'événement")),
                ('date_fin_evenement', models.DateField(blank=True, null=True, verbose_name='Date de fin (optionnel)')),
                ('lieu', models.CharField(blank=True, max_length=200, verbose_name='Lieu')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publié'), ('archive', 'Archivé')], default='brouillon', max_length=20)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('contenu', models.JSONField(blank=True, default=list, verbose_name='Contenu de la page (blocs libres)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='une_evenements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Une & Événement',
                'verbose_name_plural': 'Une & Événements',
                'ordering': ['-date_evenement', '-created_at'],
            },
        ),
    ]
