# Generated by Django 5.2.15 on 2026-07-20 09:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eden', '0009_uneevenement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du projet')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('livre', 'Livré'), ('futur', 'Projet futur')], default='en_cours', max_length=20)),
                ('type_projet', models.CharField(choices=[('lotissement', 'Lotissement'), ('mini_cite', 'Mini-cité'), ('residence', 'Résidence'), ('autre', 'Autre')], default='lotissement', max_length=20)),
                ('localisation', models.CharField(max_length=200, verbose_name='Localisation')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_courte', models.CharField(blank=True, max_length=300)),
                ('image_principale', models.ImageField(blank=True, null=True, upload_to='projets/images/')),
                ('superficie_totale', models.CharField(blank=True, max_length=50, verbose_name='Superficie totale')),
                ('nb_lots', models.PositiveIntegerField(default=0, verbose_name='Nombre de lots')),
                ('surface_lots', models.CharField(blank=True, max_length=100, verbose_name='Surface des lots')),
                ('lots_disponibles', models.PositiveIntegerField(default=0)),
                ('lots_reserves', models.PositiveIntegerField(default=0)),
                ('lots_vendus', models.PositiveIntegerField(default=0)),
                ('nb_proprietaires', models.PositiveIntegerField(default=0, verbose_name='Propriétaires')),
                ('brochure', models.FileField(blank=True, null=True, upload_to='projets/docs/', verbose_name='Brochure PDF')),
                ('plan_cadastral', models.FileField(blank=True, null=True, upload_to='projets/docs/')),
                ('grille_tarifaire', models.FileField(blank=True, null=True, upload_to='projets/docs/')),
                ('dossier_technique', models.FileField(blank=True, null=True, upload_to='projets/docs/')),
                ('annee_livraison', models.CharField(blank=True, max_length=10, verbose_name='Année de livraison')),
                ('prix_min', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['ordre', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EtapeProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name="Nom de l'étape")),
                ('icone', models.CharField(default='🔵', max_length=10, verbose_name='Icône emoji')),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('couleur', models.CharField(default='#1B4FDB', max_length=20, verbose_name='Couleur (hex)')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='eden.projet')),
            ],
            options={
                'verbose_name': 'Grande étape',
                'verbose_name_plural': 'Grandes étapes',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='ProjetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projets/galerie/')),
                ('legende', models.CharField(blank=True, max_length=200)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galerie', to='eden.projet')),
            ],
            options={
                'verbose_name': 'Image galerie',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='ProjetInfrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name="Nom de l'infrastructure")),
                ('is_realise', models.BooleanField(default=True, verbose_name='Réalisée')),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infrastructures', to='eden.projet')),
            ],
            options={
                'verbose_name': 'Infrastructure',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='SousEtapeProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom de la sous-étape')),
                ('avancement', models.PositiveSmallIntegerField(default=0, help_text='Entre 0 et 100', verbose_name='Avancement (%)')),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('etape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sous_etapes', to='eden.etapeprojet')),
            ],
            options={
                'verbose_name': 'Sous-étape',
                'ordering': ['ordre'],
            },
        ),
    ]
