# Generated by Django 5.2.15 on 2026-07-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eden', '0010_projet_etapeprojet_projetimage_projetinfrastructure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapeprojet',
            name='description',
            field=models.TextField(blank=True, verbose_name="Description de l'étape"),
        ),
    ]
