# Generated by Django 5.2.15 on 2026-07-21 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eden', '0011_etapeprojet_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name="Nom de l'agence")),
                ('type_agence', models.CharField(choices=[('siege', 'Siège Social'), ('agence', 'Agence principale'), ('bureau', 'Bureau relais')], default='agence', max_length=20)),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('adresse', models.CharField(max_length=300, verbose_name='Adresse complète')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('whatsapp', models.CharField(blank=True, max_length=30, verbose_name='WhatsApp')),
                ('email', models.CharField(blank=True, max_length=150, verbose_name='Email')),
                ('horaires', models.CharField(blank=True, default='Lun - Sam : 8h00 - 17h00', max_length=200, verbose_name='Horaires')),
                ('image', models.ImageField(blank=True, null=True, upload_to='agences/', verbose_name="Photo de l'agence")),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitude GPS')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitude GPS')),
                ('lien_itineraire', models.URLField(blank=True, verbose_name='Lien Google Maps itinéraire')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Agence',
                'verbose_name_plural': 'Agences',
                'ordering': ['ordre', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatAgence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.CharField(max_length=20, verbose_name='Valeur (ex: 3, 7+, 50+)')),
                ('label', models.CharField(max_length=100, verbose_name='Label')),
                ('icone', models.CharField(default='🏢', max_length=10, verbose_name='Icône emoji')),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Statistique agence',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='AgenceService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='Service')),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='eden.agence')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
    ]
