# Generated by Django 5.2.15 on 2026-07-22 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eden', '0012_agence_statagence_agenceservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngagementService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icone', models.CharField(default='🔒', max_length=10, verbose_name='Icône emoji')),
                ('titre', models.CharField(max_length=150, verbose_name='Titre')),
                ('description', models.CharField(max_length=300, verbose_name='Description')),
                ('couleur', models.CharField(choices=[('blue', 'Bleu'), ('red', 'Rouge'), ('green', 'Vert'), ('purple', 'Violet')], default='blue', max_length=20, verbose_name="Couleur de l'icône")),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Engagement',
                'verbose_name_plural': 'Engagements',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='EtapeProcessus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(default=0)),
                ('titre', models.CharField(max_length=150, verbose_name="Titre de l'étape")),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Description courte')),
                ('icone', models.CharField(default='✅', max_length=10, verbose_name='Icône emoji')),
                ('is_active', models.BooleanField(default=True)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Étape du processus',
                'verbose_name_plural': 'Étapes du processus',
                'ordering': ['ordre', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom')),
                ('icone', models.CharField(default='🔵', max_length=10, verbose_name='Icône emoji')),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Catégorie de service',
                'verbose_name_plural': 'Catégories de services',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(default=0, verbose_name='Numéro (affiché)')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du service')),
                ('icone', models.CharField(default='🏠', max_length=10, verbose_name='Icône emoji')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_longue', models.TextField(blank=True, verbose_name='Description longue (page détail)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Image du service')),
                ('lien_detail', models.CharField(blank=True, default='#', max_length=200, verbose_name="Lien 'En savoir plus'")),
                ('is_active', models.BooleanField(default=True)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='eden.servicecategorie', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['ordre', 'numero'],
            },
        ),
    ]
