# Generated by Django 5.2.15 on 2026-07-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eden', '0013_engagementservice_etapeprocessus_servicecategorie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademieDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('texte_loi', 'Textes de loi'), ('article', 'Articles'), ('revue', 'Revues'), ('guide', 'Guides pratiques'), ('lexique', 'Lexique du foncier'), ('video', 'Vidéothèque'), ('infographie', 'Infographies'), ('faq', 'Questions fréquentes'), ('ressource', 'Centre de ressources')], default='article', max_length=30, verbose_name='Catégorie')),
                ('titre', models.CharField(max_length=300, verbose_name='Titre')),
                ('sous_titre', models.CharField(blank=True, max_length=400, verbose_name='Sous-titre / Accroche')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image_couverture', models.ImageField(blank=True, null=True, upload_to='academie/couvertures/', verbose_name='Image de couverture')),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='academie/documents/', verbose_name='Fichier PDF')),
                ('auteur', models.CharField(blank=True, max_length=200, verbose_name='Auteur / Source')),
                ('date_publication', models.DateField(blank=True, null=True, verbose_name='Date de publication')),
                ('nb_pages', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de pages')),
                ('temps_lecture', models.CharField(blank=True, max_length=30, verbose_name='Temps de lecture')),
                ('reference_officielle', models.CharField(blank=True, max_length=300, verbose_name='Référence officielle')),
                ('numero_revue', models.CharField(blank=True, max_length=20, verbose_name='N° de revue')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publié'), ('archive', 'Archivé')], default='brouillon', max_length=20)),
                ('est_a_la_une', models.BooleanField(default=False, verbose_name='Afficher À la Une')),
                ('est_featured', models.BooleanField(default=False, verbose_name='Mis en avant')),
                ('nb_telechargements', models.PositiveIntegerField(default=0)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Document Académie',
                'verbose_name_plural': 'Documents Académie',
                'ordering': ['-date_publication', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AcademieEtapeParcours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField()),
                ('titre', models.CharField(max_length=150)),
                ('icone', models.CharField(default='📋', max_length=10)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Étape parcours',
                'ordering': ['ordre', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='AcademieFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=400)),
                ('reponse', models.TextField()),
                ('categorie_faq', models.CharField(blank=True, max_length=100, verbose_name='Catégorie FAQ')),
                ('temps_reponse', models.CharField(blank=True, max_length=100, verbose_name='Temps estimé')),
                ('est_featured', models.BooleanField(default=False, verbose_name='Question featured')),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publié')], default='publie', max_length=20)),
            ],
            options={
                'verbose_name': 'FAQ',
                'ordering': ['ordre', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AcademieStatistique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.CharField(max_length=20, verbose_name='Valeur (ex: 150+)')),
                ('label', models.CharField(max_length=100, verbose_name='Label')),
                ('icone', models.CharField(default='📋', max_length=10)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Statistique Académie',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='AcademieVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=300, verbose_name='Titre')),
                ('description', models.TextField(blank=True)),
                ('fichier_video', models.FileField(upload_to='academie/videos/', verbose_name='Fichier vidéo')),
                ('image_miniature', models.ImageField(blank=True, null=True, upload_to='academie/miniatures/', verbose_name='Miniature / Vignette')),
                ('duree', models.CharField(blank=True, max_length=20, verbose_name='Durée (ex: 08:34)')),
                ('auteur', models.CharField(blank=True, max_length=200)),
                ('date_publication', models.DateField(blank=True, null=True)),
                ('est_video_moment', models.BooleanField(default=False, verbose_name='Vidéo du moment')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publié')], default='brouillon', max_length=20)),
                ('nb_vues', models.PositiveIntegerField(default=0)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vidéo Académie',
                'verbose_name_plural': 'Vidéos Académie',
                'ordering': ['ordre', '-created_at'],
            },
        ),
    ]
