# Generated by Django 5.2.15 on 2026-07-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eden', '0014_academiedocument_academieetapeparcours_academiefaq_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journaledition',
            options={'ordering': ['-date_parution', '-created_at'], 'verbose_name': 'Édition Journal', 'verbose_name_plural': 'Éditions Journal'},
        ),
        migrations.RemoveField(
            model_name='academiedocument',
            name='numero_revue',
        ),
        migrations.RemoveField(
            model_name='journaledition',
            name='created_by',
        ),
        migrations.AddField(
            model_name='academiedocument',
            name='lien_externe',
            field=models.URLField(blank=True, verbose_name='Lien externe (optionnel)'),
        ),
        migrations.AddField(
            model_name='journaledition',
            name='type_academie',
            field=models.CharField(choices=[('journal', 'Journal EDEN'), ('article', 'Article Académie'), ('revue', 'Revue Académie'), ('guide', 'Guide Pratique')], default='journal', max_length=20, verbose_name='Type de publication'),
        ),
        migrations.AlterField(
            model_name='academiedocument',
            name='auteur',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='academiedocument',
            name='categorie',
            field=models.CharField(choices=[('texte_loi', 'Textes de loi'), ('lexique', 'Lexique du foncier'), ('video', 'Vidéothèque'), ('galerie', 'Galerie'), ('faq', 'Questions fréquentes'), ('ressource', 'Centre de ressources')], default='texte_loi', max_length=30, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='academiedocument',
            name='date_publication',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academiedocument',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='academiedocument',
            name='est_a_la_une',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='academiedocument',
            name='est_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='academiedocument',
            name='fichier_pdf',
            field=models.FileField(blank=True, null=True, upload_to='academie/documents/', verbose_name='Fichier PDF (textes de loi)'),
        ),
        migrations.AlterField(
            model_name='academiedocument',
            name='image_couverture',
            field=models.ImageField(blank=True, null=True, upload_to='academie/couvertures/'),
        ),
        migrations.AlterField(
            model_name='academiedocument',
            name='nb_pages',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academiedocument',
            name='reference_officielle',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='academiedocument',
            name='sous_titre',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='academiedocument',
            name='temps_lecture',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='journaledition',
            name='image_une',
            field=models.ImageField(blank=True, null=True, upload_to='journal/unes/'),
        ),
        migrations.AlterField(
            model_name='journaledition',
            name='numero',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='journaledition',
            name='sous_titre',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='journaledition',
            name='titre',
            field=models.CharField(max_length=300),
        ),
    ]
