# Generated by Django 5.2.15 on 2026-07-28 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eden', '0015_alter_journaledition_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journaledition',
            options={'ordering': ['-date_parution', '-created_at'], 'verbose_name': 'Édition du journal', 'verbose_name_plural': 'Éditions du journal'},
        ),
        migrations.AddField(
            model_name='journaledition',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='academiedocument',
            name='categorie',
            field=models.CharField(choices=[('texte_loi', 'Textes de loi'), ('article', 'Articles'), ('revue', 'Revues'), ('guide', 'Guides pratiques'), ('lexique', 'Lexique du foncier'), ('video', 'Vidéothèque'), ('galerie', 'Galerie'), ('faq', 'Questions fréquentes'), ('ressource', 'Centre de ressources')], default='texte_loi', max_length=30, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='journaledition',
            name='image_une',
            field=models.ImageField(blank=True, null=True, upload_to='journal/unes/', verbose_name='Image à la Une'),
        ),
        migrations.AlterField(
            model_name='journaledition',
            name='numero',
            field=models.PositiveIntegerField(unique=True, verbose_name='Numéro'),
        ),
        migrations.AlterField(
            model_name='journaledition',
            name='sous_titre',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='journaledition',
            name='titre',
            field=models.CharField(max_length=200, verbose_name="Titre de l'édition"),
        ),
    ]
