# Generated by Django 5.2.15 on 2026-07-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eden', '0016_alter_journaledition_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academiedocument',
            name='categorie',
            field=models.CharField(choices=[('texte_loi', 'Textes de loi'), ('lexique', 'Lexique du foncier'), ('video', 'Vidéothèque'), ('galerie', 'Galerie'), ('faq', 'Questions fréquentes'), ('ressource', 'Centre de ressources')], default='texte_loi', max_length=30, verbose_name='Catégorie'),
        ),
    ]
