# Generated by Django 5.2.15 on 2026-07-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eden', '0017_alter_academiedocument_categorie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journaledition',
            options={'ordering': ['-numero'], 'verbose_name': 'Édition du journal', 'verbose_name_plural': 'Éditions du journal'},
        ),
        migrations.RemoveField(
            model_name='academiedocument',
            name='lien_externe',
        ),
        migrations.RemoveField(
            model_name='journaledition',
            name='type_academie',
        ),
        migrations.AddField(
            model_name='academiedocument',
            name='numero_revue',
            field=models.CharField(blank=True, max_length=20, verbose_name='N° de revue'),
        ),
        migrations.AlterField(
            model_name='academiedocument',
            name='auteur',
            field=models.CharField(blank=True, max_length=200, verbose_name='Auteur / Source'),
        ),
        migrations.AlterField(
            model_name='academiedocument',
            name='categorie',
            field=models.CharField(choices=[('texte_loi', 'Textes de loi'), ('article', 'Articles'), ('revue', 'Revues'), ('guide', 'Guides pratiques'), ('lexique', 'Lexique du foncier'), ('video', 'Vidéothèque'), ('infographie', 'Infographies'), ('faq', 'Questions fréquentes'), ('ressource', 'Centre de ressources')], default='article', max_length=30, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='academiedocument',
            name='date_publication',
            field=models.DateField(blank=True, null=True, verbose_name='Date de publication'),
        ),
        migrations.AlterField(
            model_name='academiedocument',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='academiedocument',
            name='est_a_la_une',
            field=models.BooleanField(default=False, verbose_name='Afficher À la Une'),
        ),
        migrations.AlterField(
            model_name='academiedocument',
            name='est_featured',
            field=models.BooleanField(default=False, verbose_name='Mis en avant'),
        ),
        migrations.AlterField(
            model_name='academiedocument',
            name='fichier_pdf',
            field=models.FileField(blank=True, null=True, upload_to='academie/documents/', verbose_name='Fichier PDF'),
        ),
        migrations.AlterField(
            model_name='academiedocument',
            name='image_couverture',
            field=models.ImageField(blank=True, null=True, upload_to='academie/couvertures/', verbose_name='Image de couverture'),
        ),
        migrations.AlterField(
            model_name='academiedocument',
            name='nb_pages',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de pages'),
        ),
        migrations.AlterField(
            model_name='academiedocument',
            name='reference_officielle',
            field=models.CharField(blank=True, max_length=300, verbose_name='Référence officielle'),
        ),
        migrations.AlterField(
            model_name='academiedocument',
            name='sous_titre',
            field=models.CharField(blank=True, max_length=400, verbose_name='Sous-titre / Accroche'),
        ),
        migrations.AlterField(
            model_name='academiedocument',
            name='temps_lecture',
            field=models.CharField(blank=True, max_length=30, verbose_name='Temps de lecture'),
        ),
    ]
