# Generated by Django 5.2.15 on 2026-07-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eden', '0019_alter_journaledition_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitefoncier',
            name='prix_morcellable',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Prix minimal pour une parcelle', max_digits=15, null=True, verbose_name='Prix morcellable (FCFA)'),
        ),
        migrations.AddField(
            model_name='sitefoncier',
            name='superficie_morcellable',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Superficie minimale pour avoir une parcelle', max_digits=10, null=True, verbose_name='Superficie morcellable (m²)'),
        ),
    ]
