# Generated by Django 5.2.15 on 2026-07-31 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eden', '0020_sitefoncier_prix_morcellable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalmedia',
            name='url_externe',
        ),
        migrations.AlterField(
            model_name='journaledition',
            name='numero',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='journalmedia',
            name='fichier',
            field=models.FileField(blank=True, help_text='Image (JPG/PNG) ou vidéo locale (MP4/WebM)', null=True, upload_to='journal/medias/'),
        ),
        migrations.AlterField(
            model_name='journalmedia',
            name='type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Vidéo locale')], default='image', max_length=10),
        ),
        migrations.AlterField(
            model_name='journalpage',
            name='contenu',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='sitefoncier',
            name='prix_morcellable',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Prix minimal par m² pour la recherche de terrains', max_digits=15, null=True, verbose_name='Prix morcellable (FCFA)'),
        ),
        migrations.AlterField(
            model_name='sitefoncier',
            name='superficie_morcellable',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Superficie minimale pour la recherche de terrains', max_digits=10, null=True, verbose_name='Superficie morcellable (m²)'),
        ),
    ]
