# Generated by Django 5.2.15 on 2026-08-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eden', '0021_remove_journalmedia_url_externe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitefoncier',
            name='prix_morcellable',
        ),
        migrations.RemoveField(
            model_name='sitefoncier',
            name='superficie_morcellable',
        ),
        migrations.AlterField(
            model_name='sitefoncier',
            name='statut',
            field=models.CharField(choices=[('disponible', '🟢 Disponible'), ('site_titre', '🔵 Site titré'), ('en_cours_immatriculation', "🟡 En cours d'immatriculation"), ('titré_et_lotis', '🟣 Titré et lotis'), ('complet', '🔴 Complet'), ('prochainement', '🔷 Prochainement')], default='disponible', max_length=40),
        ),
        migrations.AlterField(
            model_name='sitefoncier',
            name='superficie_totale',
            field=models.CharField(blank=True, help_text='Ex: 2 500 m², 1.5 Ha, 500 m²', max_length=50, null=True, verbose_name='Superficie totale'),
        ),
    ]
