# Generated by Django 5.2.15 on 2026-08-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eden', '0022_remove_sitefoncier_prix_morcellable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitefoncier',
            name='morcellement',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Superficie minimale de morcellement en m²', max_digits=12, null=True, verbose_name='Morcellement (m²)'),
        ),
        migrations.AddField(
            model_name='sitefoncier',
            name='popularite',
            field=models.CharField(choices=[('du_moment', '⭐ Site du moment'), ('en_vogue', '🔥 Site en vogue'), ('demande', '📈 Site demandé'), ('rare', '💎 Site rare'), ('aucun', '— Aucun')], default='aucun', help_text='Indique si le site est du moment, en vogue, demandé ou rare', max_length=20, verbose_name='Popularité du site'),
        ),
        migrations.AlterField(
            model_name='sitefoncier',
            name='statut',
            field=models.CharField(choices=[('disponible', '🟢 Disponible'), ('site_titre', '🔵 Site titré'), ('en_cours_immatriculation', "🟡 En cours d'immatriculation"), ('titre_et_lotis', '🟣 Titré et lotis'), ('complet', '🔴 Complet'), ('prochainement', '🔷 Prochainement')], default='disponible', max_length=40),
        ),
    ]
