# Generated by Django 5.2.15 on 2026-08-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eden', '0023_sitefoncier_morcellement_sitefoncier_popularite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitefoncier',
            name='popularite',
            field=models.CharField(blank=True, help_text='Ex: Site du moment, Site en vogue, Site demandé, Site rare...', max_length=200, null=True, verbose_name='Popularité du site'),
        ),
    ]
