# Generated by Django 5.2.15 on 2026-08-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eden', '0024_alter_sitefoncier_popularite'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitefoncier',
            name='superficie_minimale_affichage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='À partir de cette superficie, le site apparaît dans les résultats.', max_digits=12, null=True, verbose_name="Superficie minimale d'affichage (m²)"),
        ),
    ]
