# Generated by Django 5.2.15 on 2026-08-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eden', '0025_sitefoncier_superficie_minimale_affichage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academiedocument',
            name='image_couverture',
            field=models.ImageField(blank=True, help_text='Sera automatiquement optimisée en WebP 1920×1080', null=True, upload_to='academie/couvertures/'),
        ),
        migrations.AlterField(
            model_name='academievideo',
            name='image_miniature',
            field=models.ImageField(blank=True, help_text='Sera automatiquement optimisée en WebP', null=True, upload_to='academie/miniatures/', verbose_name='Miniature / Vignette'),
        ),
        migrations.AlterField(
            model_name='actualitehome',
            name='image',
            field=models.ImageField(blank=True, help_text='Sera automatiquement optimisée en WebP 1920×1080', null=True, upload_to='actualites/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='agence',
            name='image',
            field=models.ImageField(blank=True, help_text='Sera automatiquement optimisée en WebP 1920×1080', null=True, upload_to='agences/', verbose_name="Photo de l'agence"),
        ),
        migrations.AlterField(
            model_name='commentairehome',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Sera automatiquement optimisée en WebP', null=True, upload_to='commentaires/', verbose_name='Photo du client'),
        ),
        migrations.AlterField(
            model_name='heroconfig',
            name='etapes_image',
            field=models.ImageField(blank=True, help_text='Sera automatiquement optimisée en WebP 1920×1080', null=True, upload_to='etapes/', verbose_name="Image technicien (section étapes d'acquisition)"),
        ),
        migrations.AlterField(
            model_name='heroconfig',
            name='image_fond',
            field=models.ImageField(blank=True, help_text='Sera automatiquement optimisée en WebP 1920×1080 (mode Hero)', null=True, upload_to='hero/', verbose_name='Image de fond du hero'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='image',
            field=models.ImageField(help_text='Sera automatiquement optimisée en WebP 1920×1080 (mode Hero)', upload_to='hero/slides/', verbose_name='Image de fond'),
        ),
        migrations.AlterField(
            model_name='imageparcelle',
            name='image',
            field=models.ImageField(help_text='Sera automatiquement optimisée en WebP 1920×1080', upload_to='parcelles/images/'),
        ),
        migrations.AlterField(
            model_name='imagesite',
            name='image',
            field=models.ImageField(help_text='Sera automatiquement optimisée en WebP 1920×1080', upload_to='sites/gallery/'),
        ),
        migrations.AlterField(
            model_name='journaledition',
            name='image_une',
            field=models.ImageField(blank=True, help_text='Sera automatiquement optimisée en WebP 1920×1080', null=True, upload_to='journal/unes/'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='image_principale',
            field=models.ImageField(blank=True, help_text='Sera automatiquement optimisée en WebP 1920×1080', null=True, upload_to='projets/images/'),
        ),
        migrations.AlterField(
            model_name='projetimage',
            name='image',
            field=models.ImageField(help_text='Sera automatiquement optimisée en WebP 1920×1080', upload_to='projets/galerie/'),
        ),
        migrations.AlterField(
            model_name='sectionlivret',
            name='image',
            field=models.ImageField(blank=True, help_text='Sera automatiquement optimisée en WebP 1920×1080', null=True, upload_to='livret/', verbose_name='Image du livret'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, help_text='Sera automatiquement optimisée en WebP 1920×1080', null=True, upload_to='services/', verbose_name='Image du service'),
        ),
        migrations.AlterField(
            model_name='sitefoncier',
            name='image_principale',
            field=models.ImageField(blank=True, help_text='Sera automatiquement optimisée en WebP 1920×1080', null=True, upload_to='sites/images/', verbose_name='Image principale'),
        ),
        migrations.AlterField(
            model_name='temoignage',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Sera automatiquement optimisée en WebP', null=True, upload_to='temoignages/'),
        ),
        migrations.AlterField(
            model_name='uneevenement',
            name='image_couverture',
            field=models.ImageField(blank=True, help_text='Sera automatiquement optimisée en WebP 1920×1080', null=True, upload_to='une_evenements/couvertures/', verbose_name='Image de couverture'),
        ),
    ]
