# Generated by Django 5.2.15 on 2026-08-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eden', '0027_alter_academiedocument_image_couverture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitefoncier',
            name='statut',
            field=models.CharField(choices=[('disponible', '🟢 Terrain Disponible'), ('site_titre', '🔵 Terrain titré'), ('en_cours_immatriculation', "🟡 Terrain En cours d'immatriculation"), ('titre_et_lotis', '🟣 Terrain Titré et lotis'), ('complet', '🔴 Complet'), ('prochainement', '🔷 Prochainement')], default='disponible', max_length=40),
        ),
    ]
