# Generated by Django 5.2.10 on 2026-09-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eden', '0028_alter_sitefoncier_statut'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoGlobale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('video', models.FileField(help_text='Formats acceptés : MP4, WebM', upload_to='videos/globale/', verbose_name='Fichier vidéo')),
                ('is_active', models.BooleanField(default=True, verbose_name="Activer l'affichage")),
                ('position', models.CharField(choices=[('bottom-right', 'En bas à droite'), ('bottom-left', 'En bas à gauche'), ('top-right', 'En haut à droite'), ('top-left', 'En haut à gauche')], default='bottom-right', max_length=20, verbose_name="Position à l'écran")),
                ('largeur', models.PositiveIntegerField(default=280, help_text='Largeur de la vidéo en pixels', verbose_name='Largeur (px)')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vidéo globale',
                'verbose_name_plural': 'Vidéos globales',
                'ordering': ['ordre'],
            },
        ),
    ]
