# Generated by Django 5.2.14 on 2026-09-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eden', '0029_videoglobale'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoglobale',
            name='hauteur',
            field=models.PositiveIntegerField(default=280, help_text='Hauteur de la vidéo en pixels', verbose_name='Hauteur (px)'),
        ),
        migrations.AlterField(
            model_name='videoglobale',
            name='largeur',
            field=models.PositiveIntegerField(default=500, help_text='Largeur de la vidéo en pixels', verbose_name='Largeur (px)'),
        ),
    ]
