# Generated by Django 5.2.10 on 2026-09-11 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eden', '0030_videoglobale_hauteur_alter_videoglobale_largeur'),
    ]

    operations = [
        migrations.CreateModel(
            name='AProposSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_section', models.CharField(choices=[('presentation', '🏢 Présentation'), ('histoire', '📖 Notre Histoire'), ('activites', '⚡ Nos Activités'), ('chiffres', '📊 Chiffres clés'), ('valeurs', '🌟 Nos Valeurs'), ('equipe', '👥 Équipe')], max_length=20, unique=True, verbose_name='Type de section')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre principal')),
                ('titre_accent', models.CharField(blank=True, max_length=200, verbose_name='Partie accentuée du titre (italique colorée)')),
                ('description', models.TextField(blank=True, verbose_name='Description sous le titre')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Section À Propos',
                'verbose_name_plural': '1. Sections À Propos',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='AProposIndicateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icone', models.CharField(choices=[('fa-calendar', '📅 Calendrier'), ('fa-pie-chart', '🥧 Camembert'), ('fa-bar-chart', '📊 Barres'), ('fa-users', '👥 Utilisateurs'), ('fa-map-marker', '📍 Localisation'), ('fa-trophy', '🏆 Trophée'), ('fa-briefcase', '💼 Mallette'), ('fa-building', '🏢 Bâtiment'), ('fa-globe', '🌍 Globe'), ('fa-star', '⭐ Étoile')], default='fa-calendar', max_length=50, verbose_name='Icône FontAwesome')),
                ('nombre', models.CharField(help_text='Ex: 1956, 25, 58 730', max_length=50, verbose_name='Valeur affichée')),
                ('suffixe', models.CharField(blank=True, help_text='Ex: M€, %, +', max_length=20, verbose_name='Suffixe (affiché en petit)')),
                ('label', models.CharField(max_length=100, verbose_name='Label')),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(limit_choices_to={'type_section': 'chiffres'}, on_delete=django.db.models.deletion.CASCADE, related_name='indicateurs', to='eden.apropossection')),
            ],
            options={
                'verbose_name': 'Indicateur clé',
                'verbose_name_plural': '3. Indicateurs clés',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='AProposEtape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.CharField(max_length=20, verbose_name='Année')),
                ('description', models.TextField(verbose_name='Description')),
                ('position', models.CharField(choices=[('gauche', 'Gauche'), ('droite', 'Droite')], default='gauche', max_length=10, verbose_name='Position')),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(limit_choices_to={'type_section': 'histoire'}, on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='eden.apropossection')),
            ],
            options={
                'verbose_name': "Étape de l'histoire",
                'verbose_name_plural': '5. Étapes (timeline histoire)',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='AProposElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icone', models.CharField(blank=True, default='🏢', max_length=10, verbose_name='Icône (emoji)')),
                ('initiales', models.CharField(blank=True, help_text='Ex: DG, JU, CA', max_length=5, verbose_name='Initiales (pour équipe)')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('sous_titre', models.CharField(blank=True, max_length=200, verbose_name='Sous-titre / Rôle')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('couleur_debut', models.CharField(blank=True, default='#1B4FDB', max_length=20, verbose_name='Couleur dégradé (début)')),
                ('couleur_fin', models.CharField(blank=True, default='#7B20B4', max_length=20, verbose_name='Couleur dégradé (fin)')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name='Ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='eden.apropossection', verbose_name='Section')),
            ],
            options={
                'verbose_name': 'Élément de section',
                'verbose_name_plural': '2. Éléments (cartes, valeurs, membres...)',
                'ordering': ['section', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='AProposTableau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text="Ex: Activités de l'année en cours", max_length=200, verbose_name='Titre du tableau')),
                ('est_pour_graphique', models.BooleanField(default=False, help_text='Cocher si ce tableau doit générer un graphique', verbose_name='Utiliser pour le graphique')),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(limit_choices_to={'type_section': 'chiffres'}, on_delete=django.db.models.deletion.CASCADE, related_name='tableaux', to='eden.apropossection')),
            ],
            options={
                'verbose_name': 'Tableau',
                'verbose_name_plural': '4. Tableaux',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='AProposLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='Libellé de la ligne')),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('tableau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='eden.apropostableau')),
            ],
            options={
                'verbose_name': 'Ligne',
                'verbose_name_plural': 'Lignes',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='AProposColonne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100, verbose_name='Titre de la colonne')),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('tableau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colonnes', to='eden.apropostableau')),
            ],
            options={
                'verbose_name': 'Colonne',
                'verbose_name_plural': 'Colonnes',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='AProposCellule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.CharField(max_length=100, verbose_name='Valeur')),
                ('colonne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eden.aproposcolonne')),
                ('ligne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cellules', to='eden.aproposligne')),
            ],
            options={
                'verbose_name': 'Cellule',
                'verbose_name_plural': 'Cellules',
                'unique_together': {('ligne', 'colonne')},
            },
        ),
    ]
