# Generated by Django 5.2.10 on 2026-09-18 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eden', '0032_sectionacademie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SectionAcademie',
        ),
    ]
