# Generated by Django 5.2.10 on 2026-09-18 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eden', '0033_delete_sectionacademie'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionAcademie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(default='🎓 EDEN GROUP ACADÉMIE', max_length=100, verbose_name='Eyebrow (texte au-dessus)')),
                ('titre_ligne1', models.CharField(default="Se former aujourd'hui", max_length=200, verbose_name='Titre ligne 1')),
                ('titre_ligne2', models.CharField(default='pour bâtir le foncier de demain', max_length=200, verbose_name='Titre ligne 2 (en couleur)')),
                ('description', models.TextField(default="L'Académie EDEN GROUP forme les professionnels, investisseurs et particuliers grâce à des modules pratiques dispensés par des experts.", verbose_name='Description')),
                ('btn_texte', models.CharField(default='Découvrir →', max_length=50, verbose_name='Texte du bouton principal')),
                ('feature1_icone', models.CharField(default='fa-solid fa-book', max_length=50, verbose_name='Feature 1 - Icône')),
                ('feature1_titre', models.CharField(default='Programmes certifiants', max_length=100, verbose_name='Feature 1 - Titre')),
                ('feature1_desc', models.CharField(default='Cours complets et pratiques', max_length=200, verbose_name='Feature 1 - Description')),
                ('feature2_icone', models.CharField(default='fa-solid fa-user-graduate', max_length=50, verbose_name='Feature 2 - Icône')),
                ('feature2_titre', models.CharField(default='Experts du domaine', max_length=100, verbose_name='Feature 2 - Titre')),
                ('feature2_desc', models.CharField(default='Formateurs expérimentés', max_length=200, verbose_name='Feature 2 - Description')),
                ('feature3_icone', models.CharField(default='fa-solid fa-compass', max_length=50, verbose_name='Feature 3 - Icône')),
                ('feature3_titre', models.CharField(default='Approche pratique', max_length=100, verbose_name='Feature 3 - Titre')),
                ('feature3_desc', models.CharField(default='Cas réels EDEN GROUP', max_length=200, verbose_name='Feature 3 - Description')),
                ('feature4_icone', models.CharField(default='fa-solid fa-certificate', max_length=50, verbose_name='Feature 4 - Icône')),
                ('feature4_titre', models.CharField(default='Certification', max_length=100, verbose_name='Feature 4 - Titre')),
                ('feature4_desc', models.CharField(default='Attestation officielle', max_length=200, verbose_name='Feature 4 - Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='academie/', verbose_name='Image centrale')),
                ('modules_titre', models.CharField(default='Document et texte réglementaire', max_length=200, verbose_name='Titre du bloc modules')),
                ('modules_lien_texte', models.CharField(default='Voir tous les documents →', max_length=100, verbose_name='Texte du lien')),
                ('is_active', models.BooleanField(default=True, verbose_name="Afficher sur la page d'accueil")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Section Académie (Accueil)',
                'verbose_name_plural': 'Section Académie (Accueil)',
            },
        ),
    ]
