# Generated by Django 5.2.10 on 2026-09-19 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eden', '0034_sectionacademie'),
    ]

    operations = [
        migrations.AddField(
            model_name='uneevenement',
            name='fichier_pdf',
            field=models.FileField(blank=True, null=True, upload_to='une_evenements/pdfs/', verbose_name='Fichier PDF'),
        ),
    ]
