# Generated by Django 5.2.10 on 2026-09-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eden', '0035_uneevenement_fichier_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='journaledition',
            name='fichier_pdf',
            field=models.FileField(blank=True, null=True, upload_to='journal/pdfs/', verbose_name='Fichier PDF'),
        ),
    ]
