# Generated by Django 5.2.14 on 2026-09-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eden', '0036_journaledition_fichier_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academiedocument',
            name='categorie',
            field=models.CharField(choices=[('texte_loi', 'Textes de loi'), ('lexique', 'Lexique du foncier'), ('brochure', 'Brochures'), ('guide_pratique', 'Guides pratiques'), ('video', 'Vidéothèque'), ('galerie', 'Galerie'), ('faq', 'Questions fréquentes'), ('ressource', 'Centre de ressources')], default='texte_loi', max_length=30, verbose_name='Catégorie'),
        ),
    ]
