# Generated by Django 5.2.14 on 2026-09-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eden', '0039_alter_academiedocument_categorie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sectionacademie',
            options={'verbose_name': 'Section Académie', 'verbose_name_plural': 'Section Académie'},
        ),
        migrations.AddField(
            model_name='sectionacademie',
            name='section_image',
            field=models.ImageField(blank=True, help_text="Image affichée dans la section Académie de la page d'accueil", null=True, upload_to='academie/section/'),
        ),
        migrations.AlterField(
            model_name='sectionacademie',
            name='btn_texte',
            field=models.CharField(default="Découvrir l'Académie", max_length=80),
        ),
        migrations.AlterField(
            model_name='sectionacademie',
            name='description',
            field=models.TextField(default='Comprendre le foncier pour investir en toute sécurité...'),
        ),
        migrations.AlterField(
            model_name='sectionacademie',
            name='eyebrow',
            field=models.CharField(default='ACADÉMIE EDEN GROUP', max_length=100),
        ),
        migrations.AlterField(
            model_name='sectionacademie',
            name='feature1_desc',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='sectionacademie',
            name='feature1_icone',
            field=models.CharField(blank=True, default='📚', max_length=10),
        ),
        migrations.AlterField(
            model_name='sectionacademie',
            name='feature1_titre',
            field=models.CharField(blank=True, default='Ressources documentaires', max_length=80),
        ),
        migrations.AlterField(
            model_name='sectionacademie',
            name='feature2_desc',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='sectionacademie',
            name='feature2_icone',
            field=models.CharField(blank=True, default='🎬', max_length=10),
        ),
        migrations.AlterField(
            model_name='sectionacademie',
            name='feature2_titre',
            field=models.CharField(blank=True, default='Vidéos pédagogiques', max_length=80),
        ),
        migrations.AlterField(
            model_name='sectionacademie',
            name='feature3_desc',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='sectionacademie',
            name='feature3_icone',
            field=models.CharField(blank=True, default='🔤', max_length=10),
        ),
        migrations.AlterField(
            model_name='sectionacademie',
            name='feature3_titre',
            field=models.CharField(blank=True, default='Lexique du foncier', max_length=80),
        ),
        migrations.AlterField(
            model_name='sectionacademie',
            name='feature4_desc',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='sectionacademie',
            name='feature4_icone',
            field=models.CharField(blank=True, default='❓', max_length=10),
        ),
        migrations.AlterField(
            model_name='sectionacademie',
            name='feature4_titre',
            field=models.CharField(blank=True, default='FAQ Expertise', max_length=80),
        ),
        migrations.AlterField(
            model_name='sectionacademie',
            name='image',
            field=models.ImageField(blank=True, help_text='Image de fond du hero de la page Académie (1920×1080 recommandé)', null=True, upload_to='academie/hero/'),
        ),
        migrations.AlterField(
            model_name='sectionacademie',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sectionacademie',
            name='modules_lien_texte',
            field=models.CharField(blank=True, default='Voir tous les modules', max_length=80),
        ),
        migrations.AlterField(
            model_name='sectionacademie',
            name='modules_titre',
            field=models.CharField(blank=True, default='Explorez nos modules', max_length=150),
        ),
        migrations.AlterField(
            model_name='sectionacademie',
            name='titre_ligne1',
            field=models.CharField(default='Le savoir foncier', max_length=150),
        ),
        migrations.AlterField(
            model_name='sectionacademie',
            name='titre_ligne2',
            field=models.CharField(default='à votre portée', max_length=150),
        ),
        migrations.AlterField(
            model_name='sectionacademie',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
