# Generated by Django 5.2.14 on 2026-09-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eden', '0040_alter_sectionacademie_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sectionacademie',
            options={'verbose_name': 'Section Académie (Accueil)', 'verbose_name_plural': 'Section Académie (Accueil)'},
        ),
        migrations.RemoveField(
            model_name='sectionacademie',
            name='section_image',
        ),
        migrations.AddField(
            model_name='sectionacademie',
            name='image_hero',
            field=models.ImageField(blank=True, null=True, upload_to='academie/hero/', verbose_name='Image — Hero page Académie (paysage 16:9)'),
        ),
        migrations.AlterField(
            model_name='sectionacademie',
            name='btn_texte',
            field=models.CharField(default='Découvrir →', max_length=50, verbose_name='Texte du bouton principal'),
        ),
        migrations.AlterField(
            model_name='sectionacademie',
            name='description',
            field=models.TextField(default="L'Académie EDEN GROUP forme les professionnels, investisseurs et particuliers grâce à des modules pratiques dispensés par des experts.", verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='sectionacademie',
            name='eyebrow',
            field=models.CharField(default='🎓 EDEN GROUP ACADÉMIE', max_length=100, verbose_name='Eyebrow (texte au-dessus)'),
        ),
        migrations.AlterField(
            model_name='sectionacademie',
            name='feature1_desc',
            field=models.CharField(default='Cours complets et pratiques', max_length=200, verbose_name='Feature 1 - Description'),
        ),
        migrations.AlterField(
            model_name='sectionacademie',
            name='feature1_icone',
            field=models.CharField(default='fa-solid fa-book', max_length=50, verbose_name='Feature 1 - Icône'),
        ),
        migrations.AlterField(
            model_name='sectionacademie',
            name='feature1_titre',
            field=models.CharField(default='Programmes certifiants', max_length=100, verbose_name='Feature 1 - Titre'),
        ),
        migrations.AlterField(
            model_name='sectionacademie',
            name='feature2_desc',
            field=models.CharField(default='Formateurs expérimentés', max_length=200, verbose_name='Feature 2 - Description'),
        ),
        migrations.AlterField(
            model_name='sectionacademie',
            name='feature2_icone',
            field=models.CharField(default='fa-solid fa-user-graduate', max_length=50, verbose_name='Feature 2 - Icône'),
        ),
        migrations.AlterField(
            model_name='sectionacademie',
            name='feature2_titre',
            field=models.CharField(default='Experts du domaine', max_length=100, verbose_name='Feature 2 - Titre'),
        ),
        migrations.AlterField(
            model_name='sectionacademie',
            name='feature3_desc',
            field=models.CharField(default='Cas réels EDEN GROUP', max_length=200, verbose_name='Feature 3 - Description'),
        ),
        migrations.AlterField(
            model_name='sectionacademie',
            name='feature3_icone',
            field=models.CharField(default='fa-solid fa-compass', max_length=50, verbose_name='Feature 3 - Icône'),
        ),
        migrations.AlterField(
            model_name='sectionacademie',
            name='feature3_titre',
            field=models.CharField(default='Approche pratique', max_length=100, verbose_name='Feature 3 - Titre'),
        ),
        migrations.AlterField(
            model_name='sectionacademie',
            name='feature4_desc',
            field=models.CharField(default='Attestation officielle', max_length=200, verbose_name='Feature 4 - Description'),
        ),
        migrations.AlterField(
            model_name='sectionacademie',
            name='feature4_icone',
            field=models.CharField(default='fa-solid fa-certificate', max_length=50, verbose_name='Feature 4 - Icône'),
        ),
        migrations.AlterField(
            model_name='sectionacademie',
            name='feature4_titre',
            field=models.CharField(default='Certification', max_length=100, verbose_name='Feature 4 - Titre'),
        ),
        migrations.AlterField(
            model_name='sectionacademie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='academie/section/', verbose_name='Image — Section accueil (carrée/portrait)'),
        ),
        migrations.AlterField(
            model_name='sectionacademie',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name="Afficher sur la page d'accueil"),
        ),
        migrations.AlterField(
            model_name='sectionacademie',
            name='modules_lien_texte',
            field=models.CharField(default='Voir tous les documents →', max_length=100, verbose_name='Texte du lien'),
        ),
        migrations.AlterField(
            model_name='sectionacademie',
            name='modules_titre',
            field=models.CharField(default='Document et texte réglementaire', max_length=200, verbose_name='Titre du bloc modules'),
        ),
        migrations.AlterField(
            model_name='sectionacademie',
            name='titre_ligne1',
            field=models.CharField(default="Se former aujourd'hui", max_length=200, verbose_name='Titre ligne 1'),
        ),
        migrations.AlterField(
            model_name='sectionacademie',
            name='titre_ligne2',
            field=models.CharField(default='pour bâtir le foncier de demain', max_length=200, verbose_name='Titre ligne 2 (en couleur)'),
        ),
        migrations.AlterField(
            model_name='sectionacademie',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière modification'),
        ),
    ]
